[build]
    publish = "build"
    command = "npm run build"

[functions]
    directory = "build"
    node_bundler = "esbuild"
    included_files = [
        "!node_modules/@xenova/transformers/**/*",
        "!node_modules/@playwright/browser-chromium/**/*",
        "!node_modules/@playwright/test/**/*",
        "!node_modules/puppeteer/**/*",
        ]

