[build]
    publish = "build/"
    command = "npm run build && npm prune --production"

[functions]
    directory = "build/"
    node_bundler = "esbuild"
    included_files = [
        "!node_modules/@xenova/transformers/**/*",
        "!node_modules/@playwright/**/*",
        "!node_modules/puppeteer/**/*",
        "!node_modules/**/*"
        ]

[context.production]
    publish = "build/"