name = "acchat"
account_id = "0181a734d34f0527e87ef1a486a2b7a7"

main = "build/index.js"
site.bucket = "build"

build.command = "npm run build"

compatibility_date = "2021-11-12"
node_compat = true

workers_dev = true


